
import type { Product, Category } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Apparel', slug: 'apparel', imageUrl: 'https://placehold.co/400x400.png', dataAiHint: 'fashion clothing' },
  { id: '2', name: 'Electronics', slug: 'electronics', imageUrl: 'https://placehold.co/400x400.png', dataAiHint: 'modern gadgets' },
  { id: '3', name: 'Home Goods', slug: 'home-goods', imageUrl: 'https://placehold.co/400x400.png', dataAiHint: 'cozy decor' },
  { id: '4', name: 'Accessories', slug: 'accessories', imageUrl: 'https://placehold.co/400x400.png', dataAiHint: 'stylish items' },
];

export const products: Product[] = [
  // Apparel
  {
    id: 'prod_001',
    name: 'AI-Designed Tee',
    description: 'A unique t-shirt with an AI-generated design. Made from 100% organic cotton.',
    images: ['https://placehold.co/500x500.png', 'https://placehold.co/450x450.png'], 
    dataAiHint: 'square placeholder one', 
    price: 29.99,
    colors: ['Black', 'White', 'Navy'],
    category: 'Apparel',
    productCode: 'AIMC-APP-001',
    slug: 'ai-designed-tee',
    stock: 1200, // Increased stock for testing 4-digit quantities
  },
  {
    id: 'prod_002',
    name: 'Cyber Hoodie',
    description: 'Stay warm with this futuristic hoodie featuring an abstract AI pattern.',
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    dataAiHint: 'hoodie fashion',
    price: 59.99,
    colors: ['Charcoal', 'Olive Green', 'Burgundy'],
    category: 'Apparel',
    productCode: 'AIMC-APP-002',
    slug: 'cyber-hoodie',
    stock: 30,
  },
  // Electronics
  {
    id: 'prod_003',
    name: 'Smart Neural Speaker',
    description: 'A voice-activated smart speaker that learns your preferences. Crystal clear sound.',
    images: ['https://placehold.co/700x700.png', 'https://placehold.co/700x700.png'],
    dataAiHint: 'smart speaker',
    price: 129.99,
    colors: ['Space Gray', 'Silver'],
    category: 'Electronics',
    productCode: 'AIMC-ELE-001',
    slug: 'smart-neural-speaker',
    stock: 20,
  },
  {
    id: 'prod_004',
    name: 'AI Powered Earbuds',
    description: 'Wireless earbuds with adaptive noise cancellation and AI sound optimization.',
    images: ['https://placehold.co/500x500.png', 'https://placehold.co/500x500.png'],
    dataAiHint: 'wireless earbuds',
    price: 89.99,
    colors: ['Midnight Black', 'Pearl White'],
    category: 'Electronics',
    productCode: 'AIMC-ELE-002',
    slug: 'ai-powered-earbuds',
    stock: 40,
  },
  // Home Goods
  {
    id: 'prod_005',
    name: 'Algorithmic Art Print',
    description: 'A beautiful canvas print generated by a generative art algorithm. Various sizes.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    dataAiHint: 'abstract art',
    price: 45.00,
    colors: ['Monochrome', 'Vibrant Spectrum'], // Representing style rather than physical color
    category: 'Home Goods',
    productCode: 'AIMC-HOM-001',
    slug: 'algorithmic-art-print',
    stock: 25,
  },
  {
    id: 'prod_006',
    name: 'Robo-Chef Assistant',
    description: 'A compact kitchen robot that helps with simple chopping and mixing tasks, guided by AI recipes.',
    images: ['https://placehold.co/600x600.png'],
    dataAiHint: 'kitchen robot',
    price: 299.00,
    colors: ['Stainless Steel', 'Matte Black'],
    category: 'Home Goods',
    productCode: 'AIMC-HOM-002',
    slug: 'robo-chef-assistant',
    stock: 15,
  },
  // Accessories
  {
    id: 'prod_007',
    name: 'Neural Network Scarf',
    description: 'A stylish silk scarf with a subtle print representing a neural network.',
    images: ['https://placehold.co/900x300.png', 'https://placehold.co/900x300.png'],
    dataAiHint: 'silk scarf',
    price: 39.99,
    colors: ['Deep Blue', 'Emerald Green', 'Ruby Red'],
    category: 'Accessories',
    productCode: 'AIMC-ACC-001',
    slug: 'neural-network-scarf',
    stock: 35,
  },
  {
    id: 'prod_008',
    name: 'Data Weave Watch',
    description: 'A minimalist watch with a watch face design inspired by data visualizations.',
    images: ['https://placehold.co/500x700.png'],
    dataAiHint: 'modern watch',
    price: 149.00,
    colors: ['Silver/Black', 'Gold/White'],
    category: 'Accessories',
    productCode: 'AIMC-ACC-002',
    slug: 'data-weave-watch',
    stock: 22,
  },
];

// Generate more products to reach at least 20 for pagination testing
const baseProductsCount = products.length;
for (let i = 0; i < 25 - baseProductsCount; i++) {
  const baseProduct = products[i % baseProductsCount];
  const categoryIndex = categories.findIndex(c => c.name === baseProduct.category);
  const cat = categories[categoryIndex % categories.length];
  
  // Ensure unique images for clones as well for variety if they are ever displayed with multiple images
  const cloneImages = baseProduct.images.map((img, idx) => {
    const url = new URL(img);
    const [dimensions] = url.pathname.substring(1).split('.');
    const [width, height] = dimensions.split('x').map(Number);
    // Use a simple increment to vary placeholder images for clones
    if (idx === 0) return `https://placehold.co/${width + i + idx + 1}x${height + i + idx + 1}.png`;
    return `https://placehold.co/${width + i + idx + 2}x${height + i + idx + 2}.png`; // For second image if it exists
  });


  products.push({
    ...baseProduct,
    id: `prod_clone_${i + 100}`,
    name: `${baseProduct.name} Clone ${i + 1}`,
    slug: `${baseProduct.slug}-clone-${i + 1}`,
    productCode: `${baseProduct.productCode}-C${i}`,
    category: cat.name, // Ensure category exists
    images: cloneImages.slice(0,2), // Ensure max 2 images for clones as well
    dataAiHint: baseProduct.dataAiHint ? `${baseProduct.dataAiHint} clone ${i+1}` : `product clone ${i+1}`,
    price: parseFloat((baseProduct.price * (1 + (i % 5) * 0.1)).toFixed(2)),
    stock: Math.floor(Math.random() * 50) + 10,
  });
}

export const getProductsByCategory = (categorySlug: string): Product[] => {
  const category = categories.find(c => c.slug === categorySlug);
  if (!category) return [];
  return products.filter(product => product.category === category.name);
};

export const getProductBySlug = (slug: string): Product | undefined => {
  return products.find(product => product.slug === slug);
};

export const getProductById = (id: string): Product | undefined => {
  return products.find(product => product.id === id);
};

