
// This file would ideally be generated by `supabase gen types typescript --project-id <your-project-id> > src/lib/database.types.ts`
// For now, I'll provide a basic structure. You should replace this with the auto-generated one.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      categories: {
        Row: {
          id: string
          name: string
          slug: string
          image_url: string | null
          data_ai_hint: string | null
          created_at: string 
        }
        Insert: {
          id?: string
          name: string
          slug: string
          image_url?: string | null
          data_ai_hint?: string | null
          created_at?: string 
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          image_url?: string | null
          data_ai_hint?: string | null
          created_at?: string 
        }
        Relationships: []
      }
      products: {
        Row: {
          id: string
          name: string
          description: string | null
          images: Json | null // Assuming array of strings: string[]
          price: number
          colors: Json | null // Assuming array of strings: string[]
          category_id: string | null // Foreign Key
          product_code: string | null
          slug: string
          stock: number
          data_ai_hint: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          images?: Json | null
          price: number
          colors?: Json | null
          category_id?: string | null
          product_code?: string | null
          slug: string
          stock: number
          data_ai_hint?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          images?: Json | null
          price?: number
          colors?: Json | null
          category_id?: string | null
          product_code?: string | null
          slug?: string
          stock?: number
          data_ai_hint?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "products_category_id_fkey"
            columns: ["category_id"]
            referencedRelation: "categories"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
